// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Powers.HappyEvent.WebApi.Data;

#nullable disable

namespace Powers.HappyEvent.WebApi.Migrations
{
    [DbContext(typeof(HappyEventDbContext))]
    [Migration("20220418082814_init_db_01")]
    partial class init_db_01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");
#pragma warning restore 612, 618
        }
    }
}
