// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Powers.HappyEvent.WebApi.Data;

#nullable disable

namespace Powers.HappyEvent.WebApi.Migrations
{
    [DbContext(typeof(HappyEventDbContext))]
    partial class HappyEventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");
#pragma warning restore 612, 618
        }
    }
}
